term.clear()
print("Kernal =Cloudpaw=")
print("Advanced programs =Cloudpaw=")
print("MemUtility2.0 =CastleMan2000=")
print("PicView =Starstruck_Studios=")
print("Button API =wieselkatze=")
print("Password Log In =Ale2610=")
print("Auto Updater =CoLDarkness=")
print("CCAPT =LNETeam=")
print("Fish Simulator =themwatt=")
print("Minecraft Stock Market =Agoldfish=")