local function Programs()
print("Default Programs Installed")
print("--------------------------")
print("advpro =Advanced Program List=")
print("programs =Basic Program List=")
print("copy =Copys files=")
print("delete =Deletes files=")
print("edit =Edits files=")
print("bg =Shell Tabs(Mutiltasking)=")
print("gps =A Global Pointing System=")
print("label =Labels a drive=")
print("monitor =Runs a program on a monitor=")
print("pastebin =Gets a script from pastebin=")
print("redstone =Redstone=")
print("shutdown =Shutsdown the computer=")
print("eject =Ejects the disk in the disk drive=")
print("dj =Plays music=")
print("Part 1 Finshed Please wait")
sleep(10)
term.clear()
print("hello =Hello World!=")
print("rename =Renames files=")
print("list =Lists programs, files, and folders in a folder=")
print("dir =Samething as list=")
print("time =Shows the time=")
print("help =Gives help=")
print("lua =A lua command line=")
print("reboot =Reboots the computer=")
print("repeat =Repeats=")
print("type =Type of thing=")
print("adventure =Text based Minecraft=")
print("alias =Alias for programs=")
print("apis =APIs inclued=")
print("clear/cls =Clears the screen=")
print("Part 2 finshed Please wait")
sleep(10)
term.clear()
print("drive =The mem left in drives=")
print("fg =More shells!=")
print("id =Shows the computer's id=")
print("paint =A paint program=")
print("shell =Does the startup programs again=")
print("worm =A simple worm game=")
print("redirection =Dan200's game called Redirection=")
print("--------------------------")
print("Done! Custom programs section comming soon!")
 end
 
Programs()
