term.clear()
print("Kernal =Cloudpaw=")
print("Advanced programs =Cloudpaw=")
print("MemUtility2.0 =CastleMan2000=")
print("PicView =Starstruck_Studios=")
print("Button API =wieselkatze=")
print("Update Checker ==")
print("CCAPT =LNETeam=")